// 购买总件数  购买总价格  最高单价  最低单价  平均价格  购买周期
export default {
  'menu.watch': '查看',
  'menu.download': '下载',
  'menu.add': '新增',
  'menu.change': '修改',
  'menu.delete': '删除',
  'menu.snkrs': '球鞋',
  'menu.snkrs.manage': '球鞋管理',
  'menu.snkrs.count': '球鞋总件数',
  'menu.snkrs.countPrice': '总价值',
  'menu.snkrs.highPrice': '最高单价',
  'menu.snkrs.lowPrice': '最低单价',
  'menu.snkrs.averagePrice': '平均价格',
  'menu.snkrs.cycle': '平均购买周期',
  'menu.snkrs.table': '球鞋ID',
  'menu.snkrs.name': '名称',
  'menu.snkrs.nickname': '球鞋别称',
  'menu.snkrs.model': '球鞋分类',
  'menu.snkrs.model.selectRange': '分类',
  'menu.snkrs.price': '价格',
  'menu.snkrs.buyDate': '购买时间',
  'menu.snkrs.buyDate.timeRange': '日期',
  'menu.snkrs.channel': '购买渠道',
  'menu.snkrs.details': '详情',
  'menu.snkrs.suitable': '穿着',
};
